### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-postgres#11]
Should prevent https://meltano.slack.com/archives/C01PKLU5D1R/p1674746485207629 from happening, although this was probably a poetry / venv local issue more than a tap-postgres thing we should keep this repo updated!

**Comment by WillDaSilva** [comment]
@visch dependabot should be configured for all MeltanoLabs repositories via https://github.com/MeltanoLabs/.github/blob/main/.github/dependabot.yml as of yesterday

**Comment by edgarrmondragon** [comment]
@WillDaSilva Looking at https://github.com/MeltanoLabs/target-csv, I can see deps are out of date, but the org-level dependabot config hasn't had any effect so far (pip deps should be updated daily)

**Comment by WillDaSilva** [comment]
@edgarrmondragon Darn. I guess we might as well delete `.github/dependabot.yml`, and start adding dependabot configs to each repository.

**Comment by visch** [comment]
Done!
