### ISSUE TITLE
'2018-07-01T00:00:00+00:00' is not a 'date' 

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-postgres#171]
I have a field with the Postgres type of `date` Date like `2018-07-01` 

The issue is that the date is being parsed like this by the tap `jsonschema.exceptions.ValidationError: '2018-07-01T00:00:00+00:00' is not a 'date' ` 

When it shouldn't have the timestamp information (Or at least I"d think it shouldn't)

**Comment by edgarrmondragon** [comment]
Probably related to https://github.com/meltano/sdk/issues/1831?

**Comment by sebastianswms** [comment]
The SDK adds timestamp to `datetime.date` on these lines: https://github.com/meltano/sdk/blob/b02d698c15c1fff8667e18e5301c65a0fd0247b5/singer_sdk/helpers/_typing.py#L477-L478
