### ISSUE TITLE
bug: JSON type mapped to string

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/tap-postgres#184]
This was reported by a couple people in slack and I also confirmed locally with a fresh install of the tap. I'm not sure if this is a bug or if its expected and just not yet supported.

If my table has a JSON column the tap treats it as a string and returns a schema like `test_json": {"type": ["string", "null"]}`. 
<img width="220" alt="Screen Shot 2023-07-24 at 2 52 50 PM" src="https://github.com/MeltanoLabs/tap-postgres/assets/27376735/da247b31-adcc-44b5-aaaf-7dd3b904689b">

**Comment by visch** [comment]
@pnadolny13  Hmm that shouldn't be happening we even have a test for this case exactly https://github.com/MeltanoLabs/tap-postgres/blob/main/tests/test_core.py#L235C22-L235C22 

Curious for sure...

**Comment by visch** [comment]
@pnadolny13  Are you on the `pypi` version or `main`? I wonder if we just haven't pushed a release out and that's causing issues?

**Comment by pnadolny13** [comment]
@visch I'm using a git url that references main. I see that test case is for jsonb, is it possible that jsonb is supported but not plain json?

**Comment by visch** [comment]
That's almost certainly the issue.... Crap

Derek Visch

Founder / CEO - Auto IDM
251 North Rose Street Suite 200, Kalamazoo, MI 49007
269-205-3280 - www.autoidm.com

**Comment by visch** [comment]
Probably as easy as  updating

```
https://github.com/MeltanoLabs/tap-postgres/blob/main/tap_postgres/client.py#L81C1-L82C45
```

To         
```
if type_name is not None and type_name in [JSONB", "JSON"]:
        return th.ObjectType().type_dict
```

Not sure I love the implementation but it would work I think!
