### ISSUE TITLE
SQLAlchemy 2 Support

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-postgres#191]
https://github.com/MeltanoLabs/tap-postgres/pull/189 We're currently failing with Sqlalchemy 2.

**Comment by edgarrmondragon** [comment]
Tests on SQLAlchemy 2 are passing now in https://github.com/MeltanoLabs/tap-postgres/pull/285

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/MeltanoLabs/tap-postgres/pull/534
