### ISSUE TITLE
Use a singleton connector

### ISSUE THREAD

**Issue by qbatten** [MeltanoLabs/tap-postgres#21]
Per [conversation here](https://github.com/meltano/sdk/issues/1352#issuecomment-1406365682), if PostgresTap used one connector, which it passes to all streams it instantiates, that would (mostly) solve #6, and it'd be a better architecture overall. This would mean that there's a single SQLAlchemy Engine opening connecitons and managing connection pooling.

**Comment by visch** [comment]
Closed with #22
