### ISSUE TITLE
Swap to use the proper shared connection in client.py get_records

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-postgres#246]
https://github.com/MeltanoLabs/tap-postgres/blob/main/tap_postgres/client.py#L238-L239

Should use `with self.connector._connect as conn` 's connection manager as that's the best practice now and will utilize connection pooling properly

**Comment by edgarrmondragon** [comment]
@visch Was this addressed by

* https://github.com/MeltanoLabs/tap-postgres/pull/247?

**Comment by visch** [comment]
I think so! @edgarrmondragon  Thank you
