### ISSUE TITLE
Feat: add `LOG_BASED` replication option

### ISSUE THREAD

**Issue by aaronsteers** [MeltanoLabs/tap-postgres#3]
It would be helpful to have an SDK-based implementation of `LOG_BASED` replication, which we'd ultimately feed back into the SDK and/or the SDK's cookiecutter.

- https://www.postgresql.org/docs/11/logicaldecoding-explanation.html#LOGICALDECODING-REPLICATION-SLOTS
- https://hevodata.com/learn/postgresql-replication-slots/

**Comment by edgarrmondragon** [comment]
@visch can this be closed?

**Comment by visch** [comment]
> @visch can this be closed?
yes
