### ISSUE TITLE
chore: Upstream breaking changes to SQLConnector - please pin sdk

### ISSUE THREAD

**Issue by qbatten** [MeltanoLabs/tap-postgres#38]
This PR https://github.com/meltano/sdk/pull/1394 makes some small breaking changes to SQLConnector.

**Recommendation: Pin the SDK to 0.19.0 in your pyproject.toml** for now.

Please take a look at [the PR description](https://github.com/meltano/sdk/pull/1394) for a deeper discussion. Here is a summary of what's changed.

Overview:
- The SQLAlchemy connection on the SQLConnector is now protected, and belongs only to the SQLConnector or it's subclasses. **Streams and other objects/functions should stop accessing the SQLConnector's engine or connection.**
- Within the SQLConnector, DB connections are opened in only one way: by using the `_connect()` method as a context manager.
- The SQLConnector uses a single engine throughout its lifetime. Connections are opened as needed and closed after each operation.

Specific code changes:
- `_connection` is gone altogether. You cannot pass it to SQLConnector and you cannot access it off of the connector. We are not caching or passing around an open DB connection anywhere anymore.
- `create_sqlalchemy_engine` and `create_sqlalchemy_connection` have been altered to use the single cached engine, and are also **deprecated**. Ideally, subclasses & other objects would stop using those methods.

Suggestions:
-  If you have any database-interacting logic that happens outside of the SQLConnector (eg if your SQLStream subclass has a get_records method that gets the SQLConnector.connection and does something with it), please move that logic onto a method on your subclass of SQLConnector and call that method from the Stream/other object.
- Wherever you're accessing the connection on SQLConnector/a subclass, please do so by using the `_connect()` method as a context manager. It's directly equivalent to [SQLAlchemy.Engine.connect()](https://docs.sqlalchemy.org/en/20/core/connections.html#basic-usage). Here's [an example of its use](https://github.com/meltano/sdk/blob/bb136040bc9fb030ba96e26df614f66a544a7ea1/singer_sdk/connectors/sql.py#L595).

**Comment by visch** [comment]
https://github.com/MeltanoLabs/tap-postgres/pull/52

**Comment by qbatten** [comment]
This is resolved; we're using 0.20.0 correctly & happily so the issue actually isn't applicable to this tap anymore.
