### ISSUE TITLE
Add maxLength to discovered schema

### ISSUE THREAD

**Issue by techtangents** [MeltanoLabs/tap-postgres#477]
Add the JSON Schema "maxLength" property when encountering varchars with a max size. e.g. a varchar(256) would have "maxLength": 256 in the schema.

This would give information to the target that's useful when creating fields. In the above example, a Postgresql or Redshift target could create a varchar(256) field.

This is particularly important in Redshift. Redshift docs advise to use the smallest possible column size for data (see [here](https://repost.aws/knowledge-center/redshift-high-disk-usage) and [here](https://docs.aws.amazon.com/redshift/latest/dg/c_best-practices-smallest-column-size.html)).

For my situation, it appears that this is causing excessive disk usage in my Redshift warehouse.

The behaviour to emit maxLength values could be a config setting. I'd probably keep it off by default.

Note: corresponding target-redshift issue here: https://github.com/TicketSwap/target-redshift/issues/105

**Comment by techtangents** [comment]
First raised at https://meltano.slack.com/archives/C069CQNHDNF/p1722991360991679

**Comment by edgarrmondragon** [comment]
This should be supported once ship https://github.com/meltano/sdk/pull/2618.

**Comment by edgarrmondragon** [comment]
@techtangents this should've been addressed by

1. https://github.com/MeltanoLabs/tap-postgres/pull/503
2. (upstream) https://github.com/meltano/sdk/pull/2651

Those changes were shipped with [v0.0.15](https://github.com/MeltanoLabs/tap-postgres/releases/tag/v0.0.15). Let me know if you find any problems with it.

Thanks!
