### ISSUE TITLE
Using uuidv7 column for incremental load fails

### ISSUE THREAD

**Issue by nikzavada** [MeltanoLabs/tap-postgres#519]
Hello everyone,

as the uuid v7 is sortable I wanted to use it as the incremental column but I got the next error:

> File ".meltano/extractors/tap-postgres/venv/lib/python3.9/site-packages/singer_sdk/helpers/_state.py", line 228, in increment_state cmd_type │
> if old_rk_value is None or not check_sorted or new_rk_value >= old_rk_value: 
> TypeError: '>=' not supported between instances of 'UUID' and 'str'

Would it be possible to fix this issue?

Thank you,
Nik

**Comment by nikzavada** [comment]
Hi @edgarrmondragon, Is there any ETA for fixing this issue? 
As I understand we can convert the UUID to string here https://github.com/meltano/sdk/blob/main/singer_sdk/helpers/_typing.py#L40 and just compare strings. Can I take a part to push this forward?

**Comment by edgarrmondragon** [comment]
@nikzavada I've logged the issue upstream and labeled it for accepting PRs. Feel free to send us a PR.

**Comment by nikzavada** [comment]
> @nikzavada I've logged the issue upstream ([meltano/sdk#2754](https://github.com/meltano/sdk/issues/2754)) and labeled it for accepting PRs. Feel free to send us a PR.

@edgarrmondragon thank you! and this is [the PR](https://github.com/meltano/sdk/pull/2755)

**Comment by edgarrmondragon** [comment]
@nikzavada this should've been fixed by `v0.0.19`, which will also land on PyPI in a couple of minutes

**Comment by nikzavada** [comment]
@edgarrmondragon The error is gone! Thank you for your help!
