### ISSUE TITLE
feat: Custom replication slot name

### ISSUE THREAD

**Issue by edgarrmondragon** [MeltanoLabs/tap-postgres#540]
> Hi everyone. I'm using tap-postgres with LOG_BASED replication method. I've successfully setup the logical replication and now able to capture insert, update, and deletes on my database.
>
> I'm running into an issue that my replication slot cannot be used by parallel extractions from the database. Is there a way to set a different replication slot name for each extractor other than tappostgres?

This should be as easy as adding new setting to `tap_postgres/tap.py` and passing it to

https://github.com/MeltanoLabs/tap-postgres/blob/e6dd19cd9946feb61ec1d41e0c694bcdab1c9cf2/tap_postgres/client.py#L343-L353

Slack Thread: https://meltano.slack.com/archives/C069CQNHDNF/p1731396392068079

**Comment by RobyBen** [comment]
I made [pull request](https://github.com/MeltanoLabs/tap-postgres/pull/543). Check pls
