### ISSUE TITLE
FATAL:  sorry, too many clients already  sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) 

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-postgres#6]
To replicate I have something like 20/30 tables in a postgres database. Created  with `podman run -e POSTGRES_PASSWORD=postgres -p 5432:5432 -h postgres -d postgres `

Maybe we're leaving a connection open for each table right now and we need to clean up?

**Comment by qbatten** [comment]
Looks like it's `_test_stream_connections` that's resulting in the error. And that's just calling Tap.run_connection_test().

Also not a real sol'n but increasing max_connections from 100 to 500 for my postgres instance allowed the tests to run & pass.

postgresql.conf
```
max_connections = 500
shared_buffers = 80MB
```

**Comment by visch** [comment]
Thanks for that @qbatten 

Without having dove for this yet my gut is that every stream we have we open another connection for, and then we don't close them until the whole process is finished running. We should really only open a connection when we're pulling data and then close the connection when we are done.

**Comment by qbatten** [comment]
Yeah agreed. Just thinking out loud / rubber-ducking here, if you see anything incorrect lmk.

AFAICT, each SQLStream has its own SQLConnector instance. Each SQLConnector has its own SQLAlchemy Engine. The Engine+connection is created when `SQLConnector.connection` is called. Right now, each of these engines is totally unrelated & unconnected to any others created by the same tap.

I'm not super familiar w SQLAlchemy, but I think we could create a Pool (probly QueuePool) and pass that to each engine. That would allow the tap to coordinate/cap the total number of connections. This could be done by overriding `create_sqlalchemy_engine` on PostgresConnector and adding a pool kwarg, which is passed directly to the engine.

**Comment by qbatten** [comment]
Other thoughts that are more diagnostic:
- I don't think a connection is opened at all during `discover_catalog_entries`
- I do think that the connection might be remaining open after get_records? I dont... see where it's closed.

**Comment by visch** [comment]
> * Yeah, why is SQLStream (singer_sdk/connectors/sql.py) creating a new engine every time it gets asked for a connection? I think that's an antipattern [see here](https://docs.sqlalchemy.org/en/20/core/connections.html#engine-disposal).

Yeah it seems that's the case right now, impacts probably all of the SQL based taps. We'd need to figure out a way to utilize pooling.

Next steps to fix this are probably
1. Make a test that fails with this (Maybe drop the max connections to 5, and create a Dockerfile to spin up a postgres instance) then create 10 tables and have the connector fail
2. Research sqlalchemy pooling. My gut says we need to make https://github.com/meltano/sdk/blob/main/singer_sdk/tap_base.py#L564 , `connector`  a class property. Override it to try with tap-postgres
3. Be sure this works (test should pass), then push up a PR for the SDK as this impacts all the tap sql connectors.

Maybe it's something else but 🤷‍♂️

**Comment by visch** [comment]
Closed by #22
