### ISSUE TITLE
Support SSH Tunnel

### ISSUE THREAD

**Issue by tayloramurphy** [MeltanoLabs/tap-postgres#69]
Related to:

* https://github.com/MeltanoLabs/target-postgres/issues/71
* https://github.com/meltano/sdk/issues/1343

**Comment by aaronsteers** [comment]
There's a stale PR with what looks like a viable implementation against the Stitch here:

https://github.com/singer-io/tap-postgres/pull/90/files#diff-1b34bc0d66624098a75021f551f3c52c81218baeab71b0d432f992e3a24aff5fR815-R836
